query product ($ID: Int!){
    
    product(ID: $ID){
        name
        description
        photos
        rate
        publisher
        created_at
        updated_at
        category
        overview
        experience
        price
        dot
        allow_return
        shipping
        worldwide
        local
        promotion
        new
        favorite
    }
    
}